// Mocks generated by Mockito 5.4.6 from annotations
// in skillswap_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:skillswap_app/models/listing_model.dart' as _i7;
import 'package:skillswap_app/models/request_model.dart' as _i9;
import 'package:skillswap_app/models/user_model.dart' as _i3;
import 'package:skillswap_app/providers/auth_provider.dart' as _i2;
import 'package:skillswap_app/providers/listing_provider.dart' as _i6;
import 'package:skillswap_app/providers/request_provider.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set currentUser(_i3.UserModel? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserCustomClaims() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCustomClaims, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> register({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? course,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #course: course,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePrivacySettings({
    required bool? showFullName,
    required bool? showCourse,
    required bool? showPhoto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrivacySettings, [], {
              #showFullName: showFullName,
              #showCourse: showCourse,
              #showPhoto: showPhoto,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSkills({
    required List<String>? canTeach,
    required List<String>? wantsToLearn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSkills, [], {
              #canTeach: canTeach,
              #wantsToLearn: wantsToLearn,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ListingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockListingProvider extends _i1.Mock implements _i6.ListingProvider {
  MockListingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.ListingModel> get listings =>
      (super.noSuchMethod(
            Invocation.getter(#listings),
            returnValue: <_i7.ListingModel>[],
          )
          as List<_i7.ListingModel>);

  @override
  List<_i7.ListingModel> get myListings =>
      (super.noSuchMethod(
            Invocation.getter(#myListings),
            returnValue: <_i7.ListingModel>[],
          )
          as List<_i7.ListingModel>);

  @override
  List<String> get savedListingIds =>
      (super.noSuchMethod(
            Invocation.getter(#savedListingIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i7.ListingModel> get savedListings =>
      (super.noSuchMethod(
            Invocation.getter(#savedListings),
            returnValue: <_i7.ListingModel>[],
          )
          as List<_i7.ListingModel>);

  @override
  set listings(List<_i7.ListingModel>? value) => super.noSuchMethod(
    Invocation.setter(#listings, value),
    returnValueForMissingStub: null,
  );

  @override
  set myListings(List<_i7.ListingModel>? value) => super.noSuchMethod(
    Invocation.setter(#myListings, value),
    returnValueForMissingStub: null,
  );

  @override
  set savedListingIds(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#savedListingIds, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadListings() =>
      (super.noSuchMethod(
            Invocation.method(#loadListings, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadMyListings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadMyListings, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createListing(_i7.ListingModel? listing) =>
      (super.noSuchMethod(
            Invocation.method(#createListing, [listing]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateListing(String? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateListing, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteListing, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isSaved(String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#isSaved, [listingId]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> loadSavedListings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedListings, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleSaved(String? uid, String? listingId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSaved, [uid, listingId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> searchListings({
    String? query = '',
    String? category = 'All',
    String? level = 'All Levels',
    String? modality = 'All Formats',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchListings, [], {
              #query: query,
              #category: category,
              #level: level,
              #modality: modality,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RequestProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestProvider extends _i1.Mock implements _i8.RequestProvider {
  MockRequestProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.RequestModel> get incoming =>
      (super.noSuchMethod(
            Invocation.getter(#incoming),
            returnValue: <_i9.RequestModel>[],
          )
          as List<_i9.RequestModel>);

  @override
  List<_i9.RequestModel> get outgoing =>
      (super.noSuchMethod(
            Invocation.getter(#outgoing),
            returnValue: <_i9.RequestModel>[],
          )
          as List<_i9.RequestModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get pendingCount =>
      (super.noSuchMethod(Invocation.getter(#pendingCount), returnValue: 0)
          as int);

  @override
  set incoming(List<_i9.RequestModel>? value) => super.noSuchMethod(
    Invocation.setter(#incoming, value),
    returnValueForMissingStub: null,
  );

  @override
  set outgoing(List<_i9.RequestModel>? value) => super.noSuchMethod(
    Invocation.setter(#outgoing, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void loadRequests(String? uid) => super.noSuchMethod(
    Invocation.method(#loadRequests, [uid]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String?> sendRequest(_i9.RequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [request]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> acceptRequest(
    String? requestId,
    Map<String, String>? confirmedSlot,
    String? requesterName,
    String? skillName,
    String? requesterId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [
              requestId,
              confirmedSlot,
              requesterName,
              skillName,
              requesterId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> declineRequest(
    String? requestId,
    String? requesterId,
    String? skillName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#declineRequest, [
              requestId,
              requesterId,
              skillName,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> endRequest(String? requestId, String? endedByUserId) =>
      (super.noSuchMethod(
            Invocation.method(#endRequest, [requestId, endedByUserId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> counterRequest(
    String? requestId,
    List<Map<String, dynamic>>? newSlots,
    String? note,
    String? requesterId,
    String? skillName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#counterRequest, [
              requestId,
              newSlots,
              note,
              requesterId,
              skillName,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
